name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15

    - name: Install LLVM and Clang
      uses: KyleMayes/install-llvm-action@v1
      with:
        version: "11.0"
        directory: ${{ runner.temp }}/llvm

    - name: Install libunwind
      run: sudo apt install libunwind-dev

    - name: Build compiler
      run: go build -v ./...

    - name: Build runtime
      run: /bin/sh ./libpea/build.sh

    - name: Test
      run: go test -v ./...