name: Pea tests
on: [push]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Build compiler
      run: go build -v ./...

    - name: Build runtime
      run: |
        export PATH=$PATH:/usr/lib/llvm-11/bin
        /bin/sh ./libpea/build.sh

    - name: Test compiler
      run: |
        export PATH=$PATH:/usr/lib/llvm-11/bin
        go test -v ./...

    - name: Test modules
      run: |
        export PATH=$PATH:/usr/lib/llvm-11/bin
        export PEA_TEST_TIMEOUT_SECONDS=300
        sh ./pea_test.sh modules
